### ISSUE TITLE
[Test] Investigate network errors

### ISSUE THREAD

**Issue by timothywangdev** [ventureum/Chainsfr#1588] opened 2020-05-07 19:31 UTC
```
 ● Email transfer form tests › Bitcoin account should have one coin

    Error: Network Error

      at createError (../../../http:/localhost:3001/static/js/0.chunk.worker.js:644:15)
      at XMLHttpRequest.handleError (../../../http:/localhost:3001/static/js/0.chunk.worker.js:187:14)
      at Suite.<anonymous> (emailTransferForm.test.e2e.js:232:3)

  ● Email transfer form tests › Transfer amount error tests

    expect(received).toEqual(expected) // deep equality

    Expected: 1
    Received: 0

      239 |       await emtPage.updateForm('account', { walletType: walletType, platformType: platformType })
      240 |       const coinList = await emtPage.getCoinList()
    > 241 |       expect(coinList.length).toEqual(1)
          |                               ^
      242 |     },
      243 |     timeout
      244 |   )

      at Object.<anonymous> (emailTransferForm.test.e2e.js:241:31)
          at runMicrotasks (<anonymous>)
```

![Screenshot from 2020-05-07 16-08-39.png](https://images.zenhubusercontent.com/5a615f3b4b5806bc2bc35c83/8a70c4b0-60f9-48ce-aa7c-24062a3d778d)

**Comment by timothywangdev** [comment] 2020-05-07 19:57
The corresponding 0.chunk.worker.js:644:15 is

![Screenshot from 2020-05-07 15-57-10.png](https://images.zenhubusercontent.com/5a615f3b4b5806bc2bc35c83/b3d2708d-2087-40e0-8ad7-31f33b9f9d9e)

**Comment by timothywangdev** [comment] 2020-05-07 20:09
Need to figure out where the error comes from: webpage or tests

**Comment by timothywangdev** [comment] 2020-05-07 20:11
erros on page should have been captured by https://github.com/ventureum/Chainsfr/blob/8de39bbd921e10b7848605d37d337fc8167677e3/src/tests/e2e/jest-environment-puppeteer/custom.setup.js#L16

**Comment by timothywangdev** [comment] 2020-05-08 00:55
![Screenshot from 2020-05-07 20-55-32.png](https://images.zenhubusercontent.com/5a615f3b4b5806bc2bc35c83/c36be8db-8c98-42c1-9d40-91d8a1d1c5c5)

**Comment by InVincible2016** [comment] 2020-05-08 17:00
- Going to try upgrading Axios

**Comment by InVincible2016** [comment] 2020-05-08 17:01
https://github.com/axios/axios/issues/1608

**Comment by InVincible2016** [comment] 2020-05-11 16:50
- Possibly caused by github action API call limit. Will check after #1594 merged.

**Comment by InVincible2016** [comment] 2020-05-20 17:19
- It seems resolved after migrating from Github Action to Travis. 
- Will re-open if the issue raises in the future.

**Closed by InVincible2016** 2020-05-20 17:19 UTC
Labels: bug
